name: Release

# Triggered when a draft released is "published" (not a draft anymore)
on:
  release:
    types: [ published ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: 11
          check-latest: true
      - name: Run tests
        run: sbt clean test